---
- name: Update and Upgrade Localhost
  hosts: localhost
  become: yes  # Necesario para obtener privilegios de root

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
      tags:
        - update

    - name: Perform APT upgrade
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
      tags:
        - upgrade
