---
- name: Install PHP
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Install PHP and required extensions
      apt:
        name:
          - php-fpm
          - php-mbstring
          - php-xml
          - php-zip
          - php-mysql
          - php-gd
          - php-curl
          - php-imagick
        state: present

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
